# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.cache/wt} [current_project]
set_property parent.project_path {D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.srcs/sources_1/new/instructionFetch.vhd}
  {D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.srcs/sources_1/new/monoimpuls.vhd}
  {D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.srcs/sources_1/new/uc.vhd}
  {D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.srcs/sources_1/new/ssd.vhd}
  {D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.srcs/sources_1/new/mem.vhd}
  {D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.srcs/sources_1/new/ex.vhd}
  {D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.srcs/sources_1/new/id.vhd}
  {D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.srcs/sources_1/new/test_env.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.srcs/constrs_1/new/const.xdc}}
set_property used_in_implementation false [get_files {{D:/MATERIALE AN 3 SEM 1/SSC/PROIECT/mips_ssc/mips_ssc.srcs/constrs_1/new/const.xdc}}]


synth_design -top test_env -part xc7k70tfbv676-1


write_checkpoint -force -noxdef test_env.dcp

catch { report_utilization -file test_env_utilization_synth.rpt -pb test_env_utilization_synth.pb }
